### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by werkington**
Adding a remote jobs site.

### CODE REVIEW

**Comment by werkington** [comment]
https://www.werkington.com/

**Comment by tramcarjobs** [comment]
@werkington your site redirects to https://www.werkington.com/  -- can you please add it to the README as such? Thanks!

**Comment by werkington** [comment]
> @werkington your site redirects to https://www.werkington.com/ -- can you please add it to the README as such? Thanks!

> @tramcarjobs I think what you're saying is change https://werkington.com/ to https://www.werkington.com/.  I have done that.  Thank you for the note.  Thanks!

**Comment by tramcarjobs** [comment]
LGTM, thanks for making that adjustment @werkington !

**Pull request merged**
