### PR TITLE
Adding teletravail.guru to the Remote jobs

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by tramcarjobs** [comment]
@cn-ds could you change your entry to https://teletravail.guru/  ? It looks like https://www.teletravail.guru/  redirects to https://teletravail.guru/ , which causes the linter to fail. Thank you!

**Comment by tramcarjobs** [comment]
@cn-ds I went ahead and made this change for you.

**Comment by cn-ds** [comment]
Thank you ! I missed the notification

**Comment by tramcarjobs** [comment]
Removed this site as it no longer loads.

**Pull request merged**
