### PR TITLE
Add GermanTechJobs as dedicated tech job board for Germany

### PR DESCRIPTION
**Pull request by Vrq**

### CODE REVIEW

**Comment by Vrq** [comment]
@tramcarjobs would you mind having a look? 
not sure why the build failed, though :(

**Comment by tramcarjobs** [comment]
@Vrq Having a look now, looks like the linter is finding a bunch of errors which need to be cleaned up.

**Comment by tramcarjobs** [comment]
Thanks @Vrq, all sorted. :)

**Comment by Vrq** [comment]
Thanks 😃

**Pull request merged**
