### PR TITLE
Add Dev Employ

### PR DESCRIPTION
**Pull request by marcelscruz**

### CODE REVIEW

**Comment by tramcarjobs** [comment]
Hey @marcelscruz , the CI check is failing with the following:

```
[L103] 307 https://www.devemploy.com/  → https://devemploy.com/
```

Could you update your link to be https://devemploy.com/ instead of https://www.devemploy.com/?

I'd also recommend adding a note, eg.:

```
* [Dev Employ](https://devemploy.com) - Hand-picked developer jobs
```

Thank you1

**Comment by marcelscruz** [comment]
Thank you for letting me know @tramcarjobs, I believe it's now fixed.

**Comment by tramcarjobs** [comment]
LGTM, thanks @marcelscruz !

**Comment by tramcarjobs** [comment]
Hey @marcelscruz , I've removed this site due to the following error:

```
 2. [L099] 404 https://devemploy.com/  
```

Feel free to add back if/when it's fixed.

**Comment by marcelscruz** [comment]
It's currently offline indeed, I'll re-add it whenever it's online again. Thanks!

**Pull request merged**
