### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by stefanwuthrich**
Added React Jobs https://reactjsjob.com
Thank you

### CODE REVIEW

**Comment by tramcarjobs** [comment]
Hey @stefanwuthrich , this LGTM! However, it looks like the RubyNow board is back up. Can you please remove that removal? :)

**Review by stefanwuthrich — COMMENTED** [review]
tks

**Comment by tramcarjobs** [comment]
Nice one, thanks @stefanwuthrich !

**Comment by tramcarjobs** [comment]
@stefanwuthrich I've removed this board as it looks dead. Feel free to re-add if/when it's back up.

**Pull request merged**
